[build-system]
requires = ["setuptools>=65.0", spounge_proto_py.egg-info"wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "spounge-proto-py"
version = "0.2.0"
description = "Generated protobuf Python packages for Spounge AI ecosystem microservices"
readme = "README.md"
license = {text = "MIT"}
authors = [
    {name = "Spounge AI Team", email = "dev@spounge.com"}
]
keywords = [
    "protobuf", "grpc", "microservices", "spounge", "ai"
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers", 
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
requires-python = ">=3.9"
dependencies = [
    "protobuf>=4.21.0,<6.0.0",
    "grpcio>=1.50.0,<2.0.0",
    "grpcio-tools>=1.50.0,<2.0.0"
]

[project.optional-dependencies]
dev = [
    "build>=0.10.0",
    "twine>=4.0.0",
    "pytest>=7.0.0"
]

[project.urls]
Homepage = "https://github.com/spoungeai/spounge-proto"
Repository = "https://github.com/spoungeai/spounge-proto"

# CRITICAL: This tells setuptools how to find your packages
[tool.setuptools.packages.find]
# Look for packages in current directory (gen/py)
where = ["."]
# Include everything that looks like a Python package
include = ["*"]
# Don't package these
exclude = ["tests*", "build*", "dist*", "*.egg-info*"]

# Include .proto files in the package
[tool.setuptools.package-data]
"*" = ["*.proto"]

[tool.setuptools]
zip-safe = false