name: Protobuf CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Buf CLI
        uses: bufbuild/buf-setup-action@v1
        with:
          version: "1.55.1"  

      - name: Check for breaking changes
        run: |
          buf breaking --against 'buf.build/spoungeai/protos:main'

      - name: Lint protos
        run: buf lint

      - name: Generate code and check for diff
        run: |
          buf generate
          git diff --exit-code
