name: Go Build CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'proto/**'
      - 'gen/go/**'
      - 'go.mod'
      - 'go.sum'
      - 'Makefile'
      - 'scripts/generate_pb.sh'
      - '.github/workflows/go-ci.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'proto/**'
      - 'gen/go/**'
      - 'go.mod'
      - 'go.sum'
      - 'Makefile'
      - 'scripts/generate_pb.sh'
      - '.github/workflows/go-ci.yml'

jobs:
  lint-proto:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup buf
      uses: bufbuild/buf-setup-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Lint proto files
      run: buf lint

  go-build-test:
    runs-on: ubuntu-latest
    needs: lint-proto
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.1'
    
    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    
    - name: Install protoc
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler
    
    - name: Install Go protobuf tools
      run: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
    
    - name: Generate Go protobuf files
      run: make gen-go
    
    - name: Build Go module
      run: make build
    
    - name: Run Go tests
      run: make test
    
    - name: Check generated files are up to date
      run: make check-generated