name: Go + TypeScript CI

on:
  push:
    branches: [main, develop]
    paths:
      - 'proto/**'
      - 'gen/go/**'
      - 'gen/ts/**'
      - 'go.mod'
      - 'go.sum'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
      - 'Makefile'
      - 'scripts/generate_pb.sh'
      - 'scripts/ts_imports.sh'
      - '.github/workflows/go-ci.yml'
      - '.github/workflows/typescript-ci.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'proto/**'
      - 'gen/go/**'
      - 'gen/ts/**'
      - 'go.mod'
      - 'go.sum'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
      - 'Makefile'
      - 'scripts/generate_pb.sh'
      - 'scripts/ts_imports.sh'
      - '.github/workflows/go-ci.yml'
      - '.github/workflows/typescript-ci.yml'

jobs:
  lint-proto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup buf
        uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint proto files
        run: buf lint

  build-and-test:
    runs-on: ubuntu-latest
    needs: lint-proto
    steps:
      - uses: actions/checkout@v4

      - name: Build protobuf generator Docker image
        run: docker build -t spoungeai/protos-gen .

      # --- Go generation & build ---
      - name: Generate Go protobuf files (inside Docker)
        run: docker run --rm -v ${{ github.workspace }}:/app -w /app spoungeai/protos-gen make gen-go

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build Go module
        run: make build

      - name: Run Go tests
        run: make test

      - name: Check Go generated files up to date (inside Docker)
        run: docker run --rm -v ${{ github.workspace }}:/app -w /app spoungeai/protos-gen make check-generated

      # --- TypeScript generation & build ---
      - name: Generate TypeScript protobuf files (inside Docker)
        run: docker run --rm -v ${{ github.workspace }}:/app -w /app spoungeai/protos-gen make gen-ts

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.2.0'
          cache: 'npm'

      - name: Install npm dependencies
        run: npm ci

      - name: Build TypeScript
        run: npm run build

      - name: Check TypeScript compilation
        run: npm run compile

      # Optionally run your TS imports script
      # - name: Run TypeScript imports script
      #   run: make ts-imports
