name: Proto-Gen Release CI

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.1'
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24.2.0'
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'
    
    - name: Install protoc
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler
    
    - name: Install tools
      run: make install-tools
    
    - name: Generate protobuf files
      run: make generate
    
    - name: Build and test
      run: |
        make build
        make test
        npm ci
        npm run build
    
    - name: Extract version
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
    
    - name: Update package.json version
      run: |
        VERSION=${{ steps.version.outputs.VERSION }}
        VERSION_NO_V=${VERSION#v}
        npm version $VERSION_NO_V --no-git-tag-version
    
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ steps.version.outputs.VERSION }}
        body: |
          ## Changes
          
          See [CHANGELOG.md](./CHANGELOG.md) for details.
          
          ## Installation
          
          **Go:**
          ```bash
          go get github.com/spoungeai/spounge-proto@${{ steps.version.outputs.VERSION }}
          ```
          
          **TypeScript/JavaScript:**
          ```bash
          npm install @spounge/proto@${{ steps.version.outputs.VERSION }}
          ```
        draft: false
        prerelease: false
    
    - name: Publish to npm
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    
    - name: Create Go module proxy cache
      run: |
        go list -m github.com/spoungeai/spounge-proto@${{ steps.version.outputs.VERSION }}
        GOPROXY=https://proxy.golang.org go list -m github.com/spoungeai/spounge-proto@${{ steps.version.outputs.VERSION }}