name: TypeScript Compile CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'proto/**'
      - 'gen/ts/**'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
      - 'scripts/generate_pb.sh'
      - 'scripts/ts_imports.sh'
      - '.github/workflows/typescript-ci.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'proto/**'
      - 'gen/ts/**'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
      - 'scripts/generate_pb.sh'
      - 'scripts/ts_imports.sh'
      - '.github/workflows/typescript-ci.yml'

jobs:
  lint-proto:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup buf
      uses: bufbuild/buf-setup-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Lint proto files
      run: buf lint

  typescript-build-test:
    runs-on: ubuntu-latest
    needs: lint-proto
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24.2.0'
        cache: 'npm'
    
    - name: Install protoc
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install TypeScript protobuf tools
      run: npm install -g ts-protoc-gen
    
    - name: Generate TypeScript protobuf files
      run: make generate
    
    - name: Build TypeScript
      run: npm run build
    
    - name: Check TypeScript compilation
      run: npm run compile
    
    - name: Run TypeScript imports script
      run: make ts-imports